import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import Link from 'next/link'


export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Blogger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, huntingcoder blog, hunting coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='/sc.js' strategy="lazyOnload"></Script> */}

      <main className={styles.main}>
        <div className={styles.imagewrap}>
          <Image className={styles.myImg} src="/homeimg.avif" width={237} height={158}/>
          {/* <img className={styles.myImg} src="/homeimg.avif" width={237} height={158} alt="coder" /> */}
        </div>
        <h1 className={styles.title}>
          <span className='dummy'>&lt;Blogger/&gt;</span>
        </h1>
        <Link className={styles.btnlink} href='/blog'><li>View Blogs</li></Link>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
